flower_identification/web_system/image_handle/urls.py
# -*- coding: utf-8 -*-
# FileName  : urls.py

from django.urls import path
from . import views

app_name = 'image_handle'
urlpatterns = [
    path('', views.index, name='index'),
    path('check/', views.check, name='check'),
    path('upload_img/', views.upload_img, name='upload_img'),
    path('check_img/', views.check_img, name='check_img'),

]

flower_identification/web_system/web_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('image_handle.urls', namespace='image_handle')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flower_identification/web_system/image_handle/models.py
from django.db import models
import django.utils.timezone as timezone
class ImageCheck(models.Model):
    file_name = models.CharField(max_length=200, verbose_name='图片名')
    file_url = models.CharField(max_length=250, verbose_name='图片URL')
    check_result = models.CharField(max_length=100, verbose_name='识别结果', blank=True)
    check_time = models.DateTimeField(default = timezone.now, verbose_name='检测时间')

    class Meta:
        db_table = 'image_check'
        verbose_name = '图片检测'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.file_name

flower_identification/web_system/image_handle/forms.py
from django import forms
from .models import ImageCheck


class MyModelForm(forms.ModelForm):
    class Meta:
        model = ImageCheck
        fields = ['file_name', 'file_url', 'check_result', 'check_time']

flower_identification/web_system/image_handle/views.py
import os
from django.conf import settings
from django.shortcuts import render
from .models import ImageCheck
from utils import restful
from utils.image_check import check_handle
from web_system.settings import admin_title, index_info
import time
from .forms import MyModelForm

import urllib.request
import urllib.parse
from lxml import etree

def index(request):
    context = {
        'title': admin_title,
        'index_info': index_info
    }

    return render(request, 'index.html', context=context)

def check(request):
    return render(request, 'check.html')


def upload_img(request):
    # 图片上传
    file = request.FILES.get('file')
    print(file.name)
    file_name = file.name
    file_name = '{}.{}'.format(int(time.time()), str(file_name).rsplit('.')[-1])
    with open(os.path.join(settings.MEDIA_ROOT, file_name), 'wb') as f:
        for chunk in file.chunks():
            f.write(chunk)
    upload_url = request.build_absolute_uri(settings.MEDIA_URL + file_name)
    ImageCheck.objects.create(file_name=file_name, file_url=upload_url)
    return restful.ok(data={'url': upload_url})


def check_img(request):
    # 图片检测
    image_url = request.POST.get('img_url')
    if not image_url:
        return restful.params_error(message='缺少必要的参数image_url')
    image_name = image_url.rsplit('/')[-1]
    image_path = os.path.join(settings.MEDIA_ROOT, image_name)
    pred_name = check_handle(image_path)
    know = query(pred_name)

    # 保存预测结果到数据库模型中
    obj = ImageCheck.objects.filter(file_name=image_name).last()
    obj.check_result = pred_name
    obj.save()
    return restful.ok(data={'pred_name': pred_name, 'query': know})

def query(content):
    # 请求地址
    url = 'https://baike.baidu.com/item/' + urllib.parse.quote(content)
    # 请求头部
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0"
    }
    # 利用请求地址和请求头部构造请求对象
    req = urllib.request.Request(url=url, headers=headers, method='GET')
    # 发送请求，获得响应
    response = urllib.request.urlopen(req)
    # 读取响应，获得文本
    text = response.read().decode('utf-8')
    # 构造 _Element 对象
    html = etree.HTML(text)
    # 使用 xpath 匹配数据，得到匹配字符串列表
    sen_list = html.xpath('//div[contains(@class,"J-summary")] /div /span/text()')
    # 过滤数据，去掉空白
    sen_list_after_filter = [item.strip('\n') for item in sen_list]
    # 将字符串列表连成字符串并返回
    return ''.join(sen_list_after_filter)

flower_identification/web_system/front/templates/check.html
{% extends 'front_base.html' %}

{% block title %}
    使用
{% endblock %}

{% block header %}
    <script src="{% static 'js/check.js' %}"></script>
    <style>
        .input-image {
            width: 500px;
            height: 400px;
            float: left;
            margin-top: 58px;
        }

        .input-image img {
            width: 100%;
            height: 100%;
        }

        .input-image span {
            margin-left: 100px
        }
        #img-check{
            position: relative;
            left: -50%;
        }
        .tit{
            position: absolute;
            left: 71%;
            top: 33%;
            font-size: 24px;
            font-style: italic;
        }
        #know-ledge{
            width: 530px;
            height: 400px;
            float: right;
            margin-top: 80px;
            margin-left: 30px;
            background-color: pink;
            padding: 10px;
            font-size: 16px;
            font-style: italic;
            text-indent: 2em;
            border: 1px solid;
            border-radius: 30px;
        }
    </style>
{% endblock %}

{% block main-container %}
    <div class="box">
        <div class="box-header page-header">
            <h1>please上传一张图片进行识别</h1>
        </div>
        <div class="row">
            <div class="col-md-12">
                <form action="" class="form-group">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="thumbnail-form">上传图片</label>
                            <div class="input-group">

                                <input type="text" class="form-control" id="img-url" name="img_url" placeholder="请点击上传，来上传一张花卉图片">
                                <input type="file" id="upload-btn" value="上传图片" style="float: right;margin-top: 20px" class="btn">

                            </div>
                        </div>

                        <button class="btn btn-primary pull-right" id="img-check">检测</button>
                        <div class="input-image">
                            <h3>This is你上传的图片</h3>
                            <img src="https://alifei02.cfp.cn/creative/vcg/800/new/VCG41N987469226.jpg" alt=""
                                 class="input-image-file">
                        </div>
                        <span class="tit">花卉介绍</span>
                        <div id="know-ledge">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

flower_identification/web_system/front/templates/front_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--视口设置，适配移动端-->
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>识别系统{% block title %}{% endblock %}</title>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'css/sweetalert.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/myalert.js' %}"></script>

    {% block header %}

    {% endblock %}

</head>
<body>
<div class="navbar navbar-inverse navbar-static-top">
    <div class="container">

        <!--定义菜单-->
        <div class="collapse navbar-collapse" id="mymenu">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'image_handle:index' %}">简介</a>
                </li>

                <li>
                    <a href="{% url 'image_handle:check' %}">检测</a>
                </li>
                <li>
                    <a href="/admin/" target="_blank">后台管理</a>
                </li>
            </ul>

        </div>
    </div>
</div>


<div class="main">
    <div class="container">
        {% block main-container %}

        {% endblock %}
    </div>
</div>

<div class="footer ">
    <div class="container">
        <div class="row footer-top">
            <div class="col-sm-6 col-lg-6">
                <h4></h4>
                <p>欢迎你加入，这里有你想要的.</p>
            </div>
            <div class="col-sm-6  col-lg-5 col-lg-offset-1">
                <div class="row about">
                    <div class="col-xs-3">
                        <h4>关于</h4>
                        <ul class="list-unstyled">
                            <li>
                                <a href="">关于我们</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-xs-3">
                        <h4>联系方式</h4>
                        <ul class="list-unstyled">
                            <li>
                                <a href="">电子邮件</a>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <hr>
        <div class="row footer-bottom">
        </div>
    </div>
</div>
</body>
</html>

flower_identification/web_system/front/templates/index.html
{% extends 'front_base.html' %}

{% block header %}

{% endblock %}

{% block main-container %}
    <div class="box">
        <div class="box-header page-header">
            <h1>{{ title }}
                <small></small>
            </h1>
        </div>
        <div class="box-body">
            <div class="box-info">
                <div class="info-image">
                    <div class="box-image">
                        <img src="{% static 'image/index1.jpg' %}" alt="">
                    </div>
                    <div class="box-image">
                        <img src="{% static 'image/index2.jpg' %}" alt="">
                    </div>
                    <div class="box-image">
                        <img src="{% static 'image/index3.jpg' %}" alt="">
                    </div>
                </div>
                <div class="box-content">
                    <p>
                        {{ index_info }}
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}